services:
  webserver:
    build: 
      context: ./bin/webserver
    ports: 
      - "8009:80"
    networks:
      - default

  mysql:
    build: ./bin/mysql
    container_name: 'png-mysql-test'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql/
      # - ./bin/mysql/my.cnf:/etc/mysql/my.cnf
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: atutor
      MYSQL_DATABASE: atutor_db
      MYSQL_USER: atutor
      MYSQL_PASSWORD: atutor
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8010:80"
    volumes:
      - ./sessions:/sessions
    networks:
      - default

networks:
  default:
    driver: bridge
