services:
  webserver:
    build:
      context: ./bin/webserver
    volumes:
      - ./sessions:/sessions  # Maps sessions folder for webserver
      - ./bin/webserver/www:/var/www/html                 # Your application files
    ports:
      - "8009:80"
    networks:
      - default

  mysql:
    build: ./bin/mysql
    container_name: 'atutor_mysql'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql/
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: atutor
      MYSQL_DATABASE: atutor_db
      MYSQL_USER: atutor
      MYSQL_PASSWORD: atutor
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8010:80"
    volumes:
      - ./sessions:/sessions  # Shared session folder for phpMyAdmin
    networks:
      - default

networks:
  default:
    driver: bridge
